# Generated by Django 5.1.7 on 2025-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragil', models.BooleanField(default=False)),
                ('liquido', models.BooleanField(default=False)),
                ('toxico', models.BooleanField(default=False)),
                ('refrigerado', models.BooleanField(default=False)),
                ('outro', models.CharField(blank=True, max_length=255)),
                ('embalada', models.BooleanField()),
                ('necessita_embalagem', models.BooleanField()),
                ('tipo_embalagem', models.CharField(blank=True, max_length=255)),
                ('urgente', models.BooleanField()),
                ('prazo_maximo', models.DateTimeField()),
                ('local_origem', models.CharField(max_length=255)),
                ('endereco_origem', models.CharField(max_length=255)),
                ('referencia_origem', models.CharField(blank=True, max_length=255)),
                ('responsavel_origem', models.CharField(blank=True, max_length=100)),
                ('telefone_origem', models.CharField(max_length=20)),
                ('data_origem', models.DateField()),
                ('hora_origem', models.TimeField()),
                ('observacao_origem', models.TextField(blank=True)),
                ('local_destino', models.CharField(max_length=255)),
                ('endereco_destino', models.CharField(max_length=255)),
                ('referencia_destino', models.CharField(blank=True, max_length=255)),
                ('responsavel_destino', models.CharField(blank=True, max_length=100)),
                ('telefone_destino', models.CharField(max_length=20)),
                ('data_destino', models.DateField()),
                ('hora_destino', models.TimeField()),
                ('observacao_destino', models.TextField(blank=True)),
                ('numero_transporte', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('cod_sap', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('valor', models.FloatField()),
                ('part_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'logimanageapp_requisicao',
            },
        ),
    ]
