# Generated by Django 5.2.1 on 2025-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peculiaridades', models.JSONField(blank=True, null=True)),
                ('outro', models.CharField(blank=True, max_length=255)),
                ('embalada', models.BooleanField()),
                ('necessita_embalagem', models.BooleanField()),
                ('tipo_embalagem', models.CharField(blank=True, max_length=255)),
                ('urgente', models.BooleanField()),
                ('prazo_maximo', models.DateTimeField()),
                ('local_origem', models.CharField(max_length=255)),
                ('endereco_origem', models.CharField(max_length=255)),
                ('referencia_origem', models.CharField(blank=True, max_length=255)),
                ('telefone_origem', models.CharField(max_length=20)),
                ('data_coleta_origem', models.DateField()),
                ('hora_coleta_origem', models.TimeField()),
                ('observacao_origem', models.TextField(blank=True)),
                ('local_coleta', models.CharField(max_length=255)),
                ('endereco_coleta', models.CharField(max_length=255)),
                ('referencia_coleta', models.CharField(blank=True, max_length=255)),
                ('telefone_coleta', models.CharField(max_length=20)),
                ('data_coleta', models.DateField()),
                ('hora_coleta', models.TimeField()),
                ('observacao_coleta', models.TextField(blank=True)),
                ('numero_transporte', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('cod_sap', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('valor', models.FloatField()),
                ('part_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
            ],
        ),
    ]
