# Generated by Django 5.1.7 on 2025-06-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requisicao',
            table='logimanageapp_requisicao',
        ),
    ]
