# Generated by Django 5.1.7 on 2025-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='responsavel_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='responsavel_origem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
