# Generated by Django 5.1.7 on 2025-06-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0002_alter_requisicao_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicao',
            old_name='peculiaridades',
            new_name='peculiaridade',
        ),
    ]
