# Generated by Django 5.1.7 on 2025-06-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0002_alter_requisicao_responsavel_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisicao',
            old_name='alias',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='requisicao',
            old_name='cod_sap',
            new_name='equipamento',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='altura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='comprimento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='embalada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='largura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='necessita_embalagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='peso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='valor',
            field=models.CharField(max_length=10),
        ),
    ]
