# Generated by Django 5.1.7 on 2025-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0003_rename_alias_requisicao_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='altura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='comprimento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='largura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='peso',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='valor',
            field=models.FloatField(),
        ),
    ]
