# Generated by Django 5.1.7 on 2025-06-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logimanageapp', '0004_alter_requisicao_altura_alter_requisicao_comprimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('valor', models.FloatField()),
            ],
            options={
                'db_table': 'logimanageapp_equipamentos',
            },
        ),
    ]
