[tool.poetry]
name = "logimanage"
version = "0.1.0a10"
description = ""
authors = ["EVANGELISTA-RIBEIRO <joaovictor.setembro@gmail.com>"]
readme = "README.md"
packages = [{ include = "logimanage" }]

[tool.poetry.dependencies]
python = ">=3.10"
django = "^5.1.7"
pytest = "^8.3.5"
python-docx = "^1.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-django = "^4.10.0"
ruff = "^0.11.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "W"]
